apiVersion: apps/v1
kind: Deployment
metadata:
  name: whatever
spec:
  template:
    spec:
      containers:
        - name: nginx
          securityContext:
            runAsNonRoot: true
            readOnlyRootFilesystem: true
